Add Roll Modifier Keys and Config Skipping
stanavdb/cosmere-rpg pull request #121
Opened 2024-10-27 11:28 UTC by MangoFVTT

**Type**  
What type of pull request is this? (e.g., Bug fix, Feature, Refactor, etc.)

- [ ] Bug fix
- [X] Feature
- [ ] Refactor
- [ ] Other (please describe):

**Description**  
Implements all the functionality for system keybindings that modify a roll and skip its configuration dialog when clicking, as discussed on Discord per issue #114. This includes functionality to swap between "skip dialog by default" and "show dialog by default" as per the system setting added in PR #117.

**Related Issue**  
Closes #114 

**How Has This Been Tested?**  
Tested all combinations of key modifiers together, and tested with the Skip Dialog by Default setting enabled/disabled. All rolls behave correctly with or without key modifiers. This includes item rolls.

**Screenshots (if applicable)**  
![image](https://github.com/user-attachments/assets/c853e61b-8c08-4e4f-880d-f76f26d97b11)

**Checklist:**  
- [X] I have commented on my code, particularly in hard-to-understand areas.
- [X] My changes do not introduce any new warnings or errors.
- [X] My PR does not contain any copyrighted works that I do not have permission to use.
- [X I have tested my changes on Foundry VTT version: 12.331

2024-10-27 11:29 UTC, MangoFVTT commented
Leaving this as draft for now because it depends on #117 to merge first.

2024-11-01 16:45 UTC, stanavdb requested changes
Testing locally, with the dialog on by default. When I use an item with an attack, it gives me the attack dialog, and when I click roll, it gives me the dialog again but without the damage. Click roll on the final dialog does perform the roll.

![image](https://github.com/user-attachments/assets/3f663495-1b37-48bd-94c6-c919ff6d99ec)
![image](https://github.com/user-attachments/assets/9123f7fa-0730-45cf-8f1c-a74f69d9b5c4)

2024-11-01 17:02 UTC, MangoFVTT commented
@stanavdb Fixed, was a variable rename I accidentally committed that wasn't caught by the typing 👍

2024-11-01 17:54 UTC, stanavdb approved these changes

2024-11-01 17:54 UTC, stanavdb commented on src/system/utils/index.ts
Everything looks good, just one minor thing I want to raise; I think we should be exporting the actor utils as `ActorUtils` instead of directly. (And just generally, anything that isn't in generic should be exported with a name imo.) 
That way we avoid confusion with certain util functions only working for actors even though they're coming from the utils import.

2024-11-01 18:52 UTC, MangoFVTT commented on src/system/utils/index.ts
If we're going to do that I vote we make every utils file its own Utils object then. So even generic would be GenericUtils, just to keep things consistent.

2024-11-02 08:35 UTC, stanavdb commented on src/system/utils/index.ts
Another alternative, we could also just not provide an index for the utils folder. That way you're always forced to specifically import what you need.

2024-11-02 08:48 UTC, MangoFVTT commented on src/system/utils/index.ts
That's a good solution yeah, I'll change to that

2024-11-02 09:14 UTC, merged