Modify goals-list and connections-list to automatically adapt to text size
stanavdb/cosmere-rpg pull request #140
Opened 2024-10-30 23:18 UTC by RostCS

**Type**  
What type of pull request is this? (e.g., Bug fix, Feature, Refactor, etc.)

- [X] Bug fix
- [ ] Feature
- [ ] Refactor
- [ ] Other (please describe):

**Description**  
Currently, the goals and connections list are not configured to scale, and automatically force a height of 2rem for all elements. This leads to overflow issues when larger goals or connections are written. 

I have modified the height to be automatic and added a small amount of padding on the top and bottom so the text looks naturally seated within the range. The overall height for a one-line goal is the same(.25 top padding, 1.5 min-size, .25 bottom padding)

**Related Issue**  
Closes #112 

**How Has This Been Tested?**  
Tested goals and connections of various sizes, and verify that all previous elements fit and still work as intended.

**Screenshots (if applicable)**  
Before:
![image](https://github.com/user-attachments/assets/3518a635-eb88-4b6f-b7cd-b043514cc39e)

After:
![image](https://github.com/user-attachments/assets/e059137a-47f7-4254-98b4-c77add2bb230)

**Checklist:**  
- [X] I have commented on my code, particularly in hard-to-understand areas.
- [X] My changes do not introduce any new warnings or errors.
- [X] My PR does not contain any copyrighted works that I do not have permission to use.
- [X] I have tested my changes on Foundry VTT version: 12.331
**Additional context**  
_Add any other context or information here that would be useful for reviewers._

2024-10-31 18:16 UTC, stanavdb requested changes
I'm running into an issue with the connections; When you expand a connection with more than a single line, it pushes the title up into the previous connection / the header.

Other than that it looks good!

![image](https://github.com/user-attachments/assets/5ef3844f-4fc7-43bd-86eb-52dbb00f95a7)

2024-10-31 18:25 UTC, RostCS commented
Ah I'll likely have to add the same autoscaling to the description submenu, did not run into that issue in my personal testing. Will fix that later today

2024-10-31 22:12 UTC, RostCS commented
Corrected 
![image](https://github.com/user-attachments/assets/6e8e43f3-1020-4732-a3af-d54ad359a701)

2024-11-01 16:34 UTC, stanavdb approved these changes
Looks good now! Thanks!

2024-11-01 16:35 UTC, merged

2024-11-01 16:38 UTC, stanavdb commented
Just for the sake of tracking who closed what issues, can you leave a comment on #112? Can't assign you, unless you leave a comment

2024-11-01 16:41 UTC, RostCS commented
> Just for the sake of tracking who closed what issues, can you leave a comment on #112? Can't assign you, unless you leave a comment

Done!